### ISSUE TITLE
Allow non-tabulated tables in shiny interface

### ISSUE THREAD

**Issue by dietrichson** [zeehio/condformat#10]
This is a feature request ;).
It would be nice to be able to control the tabulation (and page size) in shiny as well. I see that there is a parameter tabulate in the print function, however I haven't been able to force this form renderCondformat.

**Comment by zeehio** [comment]
I am not sure if I understand what you are requesting. If you mean the number of rows per page this can be done already. See the shiny demo in condformat:

```
condformat::condformat_example()
```

In code terms, if you want the user to choose between [5, 10, 15] rows per page:

```
renderCondformat({
    condformat(iris) + theme_htmlTable(number_of_entries = c(5, 10, 15))
})
```

The use of `theme_htmlTable` here may be surprising, because the `number_of_entries` argument is read by to `htmlTable::htmlTableWidget` and not `htmlTable::htmlTable`... but condformat is smart enough to pass it.

**Comment by zeehio** [comment]
Oh, I have submitted a pull request to the htmlTable package because I found a bug when `number_of_entries` is a single number: https://github.com/gforge/htmlTable/pull/32

**Comment by dietrichson** [comment]
Right, your pull request is essentially what I was asking for.

**Comment by zeehio** [comment]
Done then :+1:. Closing :-)
